### ISSUE TITLE
Add new curves in "Types of Streams"

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#110]
We've introduced four new curves in the UI, but we haven't updated the [Types of Streams](https://docs.sablier.com/concepts/protocol/stream-types) page to include them.

- Monthly Unlocks
- Timelock
- Unlock-Linear
- Unlock-Cliff

**Comment by PaulRBerg** [comment]
@andreivladbrg kind of but not really.

1. MU should contain month names on the X axis.
2. UiS can do more than MU, so we should update UiS to highlight this extra flexibility. For instance, days or weeks.

**Comment by PaulRBerg** [comment]
> MU is just a subset of UiS

Yes, which means that they are not the same thing.

> `FunctionPlot` component displays "time" on the X axis

So is it not possible to display something else?

> change the component or add another that specifically labels the X axis as "months"

This

**Comment by PaulRBerg** [comment]
> why not include some comments about MU at the UiS shape, can't we do this?

The masses like concrete examples. They do not think mathematically.

The documentation site is meant to dumb down Sablier.

> it requires to change the current function or to implement a new one

Let's do it

**Comment by andreivladbrg** [comment]
> The masses like concrete examples. They do not think mathematically
> documentation site is meant to dumb down Sablier

i agree that the masses like concrete examples, and that's why we include them at the interface level. 

however, my understanding is that the documentation site is intended for developers, who are presumably technical. if that's not the case (if it's not specifically for developers) then i agree

**Comment by PaulRBerg** [comment]
developers like concrete examples, too

**Comment by andreivladbrg** [comment]
so, you're saying that keeping UiS, along with comments on how this method can achieve monthly unlocks, does not represent a concrete example for developers - fair enough

how should the curve look like? same number of unlocks as UiS, or less/multiple?

**Comment by PaulRBerg** [comment]
Yes

> how should the curve look like? same number of unlocks as UiS, or less/multiple?

I answered this in a comment above. We should make it different (fewer, more, it doesn't matter) so that they are visually differentiable

**Comment by smol-ninja** [comment]
After V2.2, wouldn't we use Lockup Tranched to create unlock-in-steps and unlock-each-month streams in the UI? If yes, then why are we including them to Lockup dynamic section in doc?

**Comment by andreivladbrg** [comment]
You are right Shub, thanks for pointing out. These shapes will be placed under Lockup Tranched section.
