### ISSUE TITLE
Write guide about how to make custom deployments

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#127]
## Task

Custom deployments can be made like this:

- Ask for permission to receive a [BUSL license grant](https://github.com/sablier-labs/v2-core/blob/main/LICENSE.md)
- Follow the [technical instructions](https://sablier.notion.site/How-to-Deploy-Sablier-V2-Contracts-20fe630984e04c6bb35fa3f9dd293cee?pvs=4)

## Context

<img width="400" alt="SCR-20240108-rxqg" src="https://github.com/sablier-labs/v2-docs/assets/8782666/90319606-a05d-4cc2-a0d9-0adb387bbcd8">
<img width="400" alt="SCR-20240108-rxqy" src="https://github.com/sablier-labs/v2-docs/assets/8782666/65cf265c-0966-441f-93e7-5594f98c83d6">

**Comment by smol-ninja** [comment]
Resolved in https://github.com/sablier-labs/docs/pull/174.

https://docs.sablier.com/contracts/v2/guides/custom-deployments
