### ISSUE TITLE
Table with estimated gas fees

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#128]
Here:

https://docs.sablier.com/concepts/protocol/fees#gas-fees

Just like here:

https://docs.sablier.com/contracts/v1/guides/gas-costs

**Comment by smol-ninja** [comment]
Included:
1. https://v2-docs-4g3o3aogr-sablier.vercel.app/contracts/v2/gas-costs/v2-core
2. https://v2-docs-4g3o3aogr-sablier.vercel.app/contracts/v2/gas-costs/v2-periphery
