### ISSUE TITLE
Deploy preview for new PRs

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/docs#139]
Currently, Vercel only deploys the production website for docs, the deployment for the preview website fails because customs builds are ignored in its configurations.

<img width="868" alt="Screenshot 2024-04-03 at 17 25 51" src="https://github.com/sablier-labs/docs/assets/6676622/7ed21c33-4519-44ed-9e2c-f04ca9401a83">

However, It would be useful to deploy a preview version of the website for new PRs.

Related https://github.com/sablier-labs/docs/pull/138.

**Comment by PaulRBerg** [comment]
I updated the "Ignored Build Step" settings:

<img width="400" alt="SCR-20240414-pwag" src="https://github.com/sablier-labs/docs/assets/8782666/3c8c45fa-8cf8-418c-a981-9e5dfd6aa789">
