### ISSUE TITLE
Add more informations about Airstream Campaigns unicity

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/docs#140]
The idea is to mention that you can't have the same Airstream Campaign deployed twice, this is due to how CREATE2 works and the fact we hash in the salt all relevant parameters.

**Comment by andreivladbrg** [comment]
Should we close this since we will no longer use `CREATE2` on the next release? @razgraf @PaulRBerg

**Comment by smol-ninja** [comment]
Reopening this issue as we have decided to switch back to CREATE2: https://github.com/sablier-labs/v2-periphery/issues/353

**Comment by smol-ninja** [comment]
This is practically not possible so should we skip it? I don't think anybody would want to deploy the exactly same airstream twice. 

By adding this, it may confuse readers.
