### ISSUE TITLE
Add gas costs for the different types of streams

### ISSUE THREAD

**Issue by maxdesalle** [sablier-labs/docs#143]
![CleanShot 2024-04-26 at 20 46 02@2x](https://github.com/sablier-labs/docs/assets/70470326/c022d29c-8380-46c3-a5a9-be4dd11d30e8)

**Comment by PaulRBerg** [comment]
This would be also useful for user comms.

We have been frequently asked about the costs of creating streams.

**Comment by smol-ninja** [comment]
I've worked on this [benchmark PR](https://github.com/sablier-labs/v2-core/blob/test/benchmarks/benchmarks/SablierV2LockupDynamic.md). I can add new rows to include gas usage for different stream shapes. But the question I would like to ask is: how many segments should be considered for the benchmark? 10, 50, 100?

**Comment by andreivladbrg** [comment]
the exact [shapes](https://docs.sablier.com/concepts/protocol/stream-types) from the app and the docs are in the [examples](https://github.com/sablier-labs/examples) repo, we can simply add there a benchmark in the tests

**Comment by smol-ninja** [comment]
Makes sense to add them in the `examples` repo itself.

**Comment by andreivladbrg** [comment]
Merged 223e6b640cef1d223e0f018d6911aa4cf53e4348
