### ISSUE TITLE
The diagram for the access control of the withdraw function does not display correctly on Brave/ Windows

### ISSUE THREAD

**Issue by IaroslavMazur** [sablier-labs/docs#15]
On the [Access Control](https://sablier-v2-docs.vercel.app/contracts/v2/reference/access-control) page, the diagram for the **Withdraw** workflow appears incomplete.

Here's how it looks with the Light Theme: 
![image](https://user-images.githubusercontent.com/22785348/227953774-84143b7d-f56c-4fe0-b1d4-417e00f5a6d7.png)

And here's the Dark Theme look:
![image](https://user-images.githubusercontent.com/22785348/227953826-8b912eb1-7f8b-496a-ab88-322d49e992dc.png)

I've reproduced this issue in Brave (the browser I normally use) and Edge (the only other browser I have installed rn 😆)

**Comment by PaulRBerg** [comment]
@IaroslavMazur, are you still experiencing this behavior?

**Comment by IaroslavMazur** [comment]
> @IaroslavMazur, are you still experiencing this behavior?

Yes, the issue is still reproducible.

**Comment by smol-ninja** [comment]
@IaroslavMazur can you please check if the issue still exists? I am using Brave and it looks fine to me.

**Comment by PaulRBerg** [comment]
Bump @IaroslavMazur, can you double check this please?

**Comment by IaroslavMazur** [comment]
> [@IaroslavMazur](https://github.com/IaroslavMazur) can you please check if the issue still exists? I am using Brave and it looks fine to me.

Sorry for missing your message, @smol-ninja 😢

> @IaroslavMazur, can you double check this please?

The diagram from the OP is no longer present in the current version of the docs, but I went through all of the current diagrams on that page - and they appear to be alright on Brave & Windows now - for both the Light and the Dark themes.

Thanks for reminding me about this! 🙏

---

Closing the issue.
