### ISSUE TITLE
Document "MAX_SEGMENT_COUNT" and "MAX_TRANCHE_COUNT"

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#152]
The current value is 300, but it is not documented anywhere.

When we deploy the new contracts, we will have different values for each chain.

https://github.com/sablier-labs/v2-core/issues/872

**Comment by smol-ninja** [comment]
- https://v2-docs-4g3o3aogr-sablier.vercel.app/concepts/protocol/segments#requirements (2nd point)
- https://v2-docs-4g3o3aogr-sablier.vercel.app/concepts/protocol/tranches#requirements (2nd point)

**Comment by PaulRBerg** [comment]
There appears to be an extra `$$` in the first link.

<img width="300" alt="SCR-20240704-sbxn" src="https://github.com/sablier-labs/docs/assets/8782666/a2ab08bd-8627-4db9-afa2-210366417c7d">

**Comment by PaulRBerg** [comment]
Otherwise, it looks good!

**Comment by smol-ninja** [comment]
Its been fixed now.
