### ISSUE TITLE
Mention the importance of using `SD59x18` in Lockup Dynamic

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/docs#153]
We have been asked on several occasions why did we prefer `SD59x18` over `UD60x18` for segment amount in Lockup dynamic calculations.

Therefore, document its important in the Sablier docs.

**Comment by PaulRBerg** [comment]
TL;DR needed for exponentiation with sub-unitary bases

**Comment by smol-ninja** [comment]
I couldn't find a place in the docs to document this. This has nothing to do with users as its more related to the internals of the contract. So imo, there is no need to document it in the docs.

**Comment by PaulRBerg** [comment]
Sounds good
