### ISSUE TITLE
Add information about geographical restrictions in Airstreams

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/docs#162]
The appropriate section would be [Apps](https://docs.sablier.com/apps/overview) since the geoblocking can only apply to the interface.

**Comment by razgraf** [comment]
There's a section in https://v2-docs-jyalwxu5q-sablier.vercel.app/apps/features/drops#advanced-settings that includes geo-fencing.

**Comment by smol-ninja** [comment]
Nice. We can close this issue then.

**Comment by smol-ninja** [comment]
Closing this as it is fixed in https://docs.sablier.com/apps/features/airdrops#geo-fencing--geographical-restrictions.
