### ISSUE TITLE
Add section about "Cancelability" under "Concepts"

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#163]
It would be helpful to add a section about Cancelability in the Concepts section.

We keep getting questions about this:

<img width="350" alt="SCR-20240724-lnle" src="https://github.com/user-attachments/assets/a1bc3710-534b-4f67-b893-f7a5c719042e">

**Comment by PaulRBerg** [comment]
This would also clarify situations like this:

<img width="404" alt="SCR-20240724-loou" src="https://github.com/user-attachments/assets/6f0f0edd-b68b-4f04-8681-4cb25377aa30">

**Comment by maxdesalle** [comment]
https://github.com/sablier-labs/docs/commit/1fe7f88384c5454f53380e9172da67e8577ce6bf
