### ISSUE TITLE
Include a note in Deployment Addresses about app-level aliases

### ISSUE THREAD

**Issue by razgraf** [sablier-labs/docs#166]
A user made me realize we should add a note in the [deployments](https://docs.sablier.com/contracts/v2/deployments) page that mentions what aliases we used for each version of the contracts.

<img width="1020" alt="Screenshot 2024-07-26 at 14 58 36" src="https://github.com/user-attachments/assets/0a0ab281-b0c0-4865-8433-51be0bfe1b28">

Maybe we can provide a table in this info box where we could say something like: 

> [!NOTE]
> Came here looking for the previous V2 deployments? Click below to see previous versions as well as in-app aliases assigned under our naming [convention](https://docs.sablier.com/api/subgraphs/protocol/structure#identifying).
> 
> | Version | Aliases |
> | --- | --- |
> | v2.2 (current) |  LD3 (Lockup Dynamic), LL3 (Lockup Linear), LT3 (Lockup Tranched) |
> | [v2.1](https://docs.sablier.com/contracts/v2/deployments/v2.1) |  LD2 (Lockup Dynamic), LL2 (Lockup Linear) |
> | [v2.0](https://docs.sablier.com/contracts/v2/deployments/v2.1)  |  LD (Lockup Dynamic), LL (Lockup Linear) |
>
> Or maybe you're looking for V1? [Click here](https://docs.sablier.com/contracts/v1/deployments).

**Comment by PaulRBerg** [comment]
makes sense to me
