### ISSUE TITLE
Search result redirects to 404

### ISSUE THREAD

**Issue by tukwan** [sablier-labs/docs#213]
The search results appear on the list, but when I click them, it redirects to 404.

https://github.com/user-attachments/assets/9d5aa96f-70a9-4d2f-bf46-b3b487151250

**Comment by PaulRBerg** [comment]
This is because Algolia crawls our site every week. However, as @maxdesalle said [here](https://github.com/sablier-labs/docs/issues/23#issuecomment-1632434919), it is possible to manually trigger a re-index.

Max, could you please do that?

**Comment by maxdesalle** [comment]
Should be fixed 🫡
