### ISSUE TITLE
Add relational diagram for how streams are represented in Flow contract (as a monolith)

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#222]
I just noticed that the [Flow diagrams](https://docs.sablier.com/reference/flow/diagrams) don't contain a diagram analogous to the ones in [Lockup](https://docs.sablier.com/reference/lockup/diagrams), specifically:

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/c3fb68e8-99ad-4eca-a45a-adf31185d8f2" />

**Comment by smol-ninja** [comment]
Thats a diagram to visualize storage layout. We have [one in Flow](https://docs.sablier.com/reference/flow/diagrams#flow-storage-layout) as well.

**Comment by PaulRBerg** [comment]
OK then the task is modify that diagram so that it appears:

- Flow contract
- Stream 1
- Stream 2

It's not clear whose "Storage" this is:

<img width="250" alt="Image" src="https://github.com/user-attachments/assets/cab29872-96c1-48c9-926d-3fc45c9db7a1" />
