### ISSUE TITLE
"ISablierV2NFTDescriptor" hyperlink not working

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#46]
## Problem

1. Go here: https://docs.sablier.com/contracts/v2/reference/core/contract.SablierV2NFTDescriptor
2. Click on `ISablierV2NFTDescriptor`
3. "Page Not Found"

## Cause

Running `pnpm run build` in production produces the following warnings:

```text
[WARNING] Docs markdown link couldn't be resolved: (/docs/contracts/v2/reference/core/interfaces/interface.ISablierV2NFTDescriptor.md) in "/vercel/path0/docs/contracts/v2/reference/core/contract.SablierV2NFTDescriptor.md" for version current
--
17:41:44.685 | [WARNING] Docs markdown link couldn't be resolved: (/docs/contracts/v2/reference/core/interfaces/interface.ISablierV2NFTDescriptor.md) in "/vercel/path0/docs/contracts/v2/reference/core/contract.SablierV2NFTDescriptor.md" for version current
17:41:52.983 | [WARNING] Docs markdown link couldn't be resolved: (/docs/contracts/v2/reference/core/interfaces/interface.ISablierV2NFTDescriptor.md) in "/vercel/path0/docs/contracts/v2/reference/core/contract.SablierV2NFTDescriptor.md" for version current
17:41:52.983 | [WARNING] Docs markdown link couldn't be resolved: (/docs/contracts/v2/reference/core/interfaces/interface.ISablierV2NFTDescriptor.md) in "/vercel/path0/docs/contracts/v2/reference/core/contract.SablierV2NFTDescriptor.md" for version curren
```

See, for example, this [Vercel deployment](https://vercel.com/sablier/v2-docs/C7R55jqPAmpHsz9WihD1xmkXNh5w).

It is a strange bug because:

1. I cannot reproduce it locally on my machine - running `pnpm run build` generates no warnings and the `ISablierV2NFTDescriptor` hyperlink works.
2. I've looked at the URLs themselves multiple times, and I've run out of ideas about what could go wrong. Might this be a bug in Docusaurus?
3. The hyperlinks in the other contracts, e.g. `SablierV2LockupLinear`, are working just fine! and they are analogous.

## Help Wanted

Cc @razgraf you said that you've gotten the same warnings locally - would you mind taking a quick look at this issue?

However, if you cannot reproduce either, let's just mark this bug as "backlog" and move on.

## Resources

Potentially related: the Docusaurus docs on [Markdown links](https://docusaurus.io/docs/markdown-features/links).

**Comment by razgraf** [comment]
Was experiencing this in both `pnpm build` and `pnpm start` by the way! Sure, I'll try to figure out a fix, although I've already spent an hour searching through Stack and Github issues the other day (when I discovered the problem) and nothing came up 🤔 Will assign some more time to this after I finish my part on the content side.

**Comment by PaulRBerg** [comment]
Thanks for checking - don't worry. In the grand scheme of things, this bug doesn't matter. Let's focus on our other launch priorities.

**Comment by PaulRBerg** [comment]
I think I have figured out what's going on - for some reason, the name of the interface contains a lowercase `Nft` instead of an uppercase `NFT`:

<img width="393" alt="SCR-20240101-nhvp" src="https://github.com/sablier-labs/v2-docs/assets/8782666/9904dad3-5d9c-4854-aa9d-cda0c1149c9e">

**Comment by PaulRBerg** [comment]
Re-opening because it turns out that the warning is appearing again:

https://github.com/sablier-labs/docs/pull/137#issuecomment-2061882541

**Comment by PaulRBerg** [comment]
Fixed via https://github.com/sablier-labs/docs/commit/82480490d0a0558e3f1b429370062eed15f122cd.

It was a capitalization issue again.

Cc @smol-ninja @andreivladbrg for when you will re-generate the docs for V2.2, keep this in mind
