### ISSUE TITLE
Fix issue in "Create a Stream" pagination link

### ISSUE THREAD

**Issue by scorpion9979** [sablier-labs/docs#54]
While reading the Sablier V2 docs, I noticed that the "Create a Stream" pagination link in [Guides / Configure Your Local Environment](https://docs.sablier.com/contracts/v2/guides/local-environment) is not clickable.

Screenshot:

![image](https://github.com/sablier-labs/v2-docs/assets/4002635/c99ff70c-8c56-476c-adba-00596553f384)

**Comment by PaulRBerg** [comment]
Thank you! I've managed to reproduce it.

**Comment by PaulRBerg** [comment]
Fixed by #154
