### ISSUE TITLE
Reduce size of screenshot image files

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#60]
The screenshots in the "Apps" section are taking a while to load (on an okay-ish Internet connection):

https://github.com/sablier-labs/v2-docs/assets/8782666/b71aac25-2128-46bf-b74b-a1aed0f9de00

**Comment by smol-ninja** [comment]
This seems to have been resolved in the [latest commits](https://github.com/sablier-labs/docs/commit/2d85fa7248a7459f86f0bb8f104041bf14402d79). Should I close it?
