### ISSUE TITLE
Document npm packages explicitly

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#78]
We have two npm packages that export the contract artifacts:

- [`@sablier/v2-core`](https://www.npmjs.com/package/@sablier/v2-core)
- [`@sablier/v2-periphery`](https://www.npmjs.com/package/@sablier/v2-periphery)

We should provide a bespoke guide for how to install and interact with them.

**Comment by smol-ninja** [comment]
Don't the following guides document it already?

- [Create an Airstream](https://v2-docs-478yj2s23-sablier.vercel.app/guides/lockup/examples/create-airstream)
- [Create a Batch of Lockup Linear Streams](https://v2-docs-478yj2s23-sablier.vercel.app/guides/lockup/examples/batch-create-streams/batch-lockup-linear)

**Comment by PaulRBerg** [comment]
They do but what about those users uninterested in traversing the tutorials and just wanting to install the packages directly?

I'm thinking to simply expand upon this paragraph:

> In addition, familiarity with Ethereum and Solidity is requisite.
 
Like so:
 
 > In addition, familiarity with Ethereum and Solidity is requisite.
 > Node.js is needed for installing our npm packages `@sablier/v2-core` and `@sablier/v2-periphery`.

**Comment by smol-ninja** [comment]
> They do but what about those users uninterested in traversing the tutorials and just wanting to install the packages directly?

Agree with this. We have the following two guides:
1. https://v2-docs-20isq65bp-sablier.vercel.app/guides/lockup/examples/local-environment#start-from-scratch
2. https://v2-docs-20isq65bp-sablier.vercel.app/guides/flow/examples/local-environment#start-from-scratch

These two include a mini guide on how to install npm package and interact with them. Titles can be more bespoke such as:

1. Pre-requisites
2. Setting up from template
3. Install Lockup npm packages
4. Writing your first contract

Then users can refer to "Install Lockup npm packages" to find explicit guide for installing npm packages. What do you think?

**Comment by PaulRBerg** [comment]
I like your suggested approach

**Comment by smol-ninja** [comment]
Done through https://github.com/sablier-labs/docs/pull/186/commits/18a0aef9990bc2de68d7e77fda00f710f6d20e3c and https://github.com/sablier-labs/docs/pull/186/commits/a0a0bdf7c40411329add70cf830f550a595dc347 in https://github.com/sablier-labs/docs/pull/186.

## Previews

1. [Install Lockup npm packages](https://v2-docs-j8cnhy2gc-sablier.vercel.app/guides/lockup/examples/local-environment#install-lockup-npm-packages)
2. [Install Flow npm package](https://v2-docs-j8cnhy2gc-sablier.vercel.app/guides/flow/examples/local-environment#install-flow-npm-package)
