### ISSUE TITLE
Mention "Grants" in "Use Cases" page

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/docs#81]
In https://docs.sablier.com/concepts/use-cases

**Comment by smol-ninja** [comment]
https://v2-docs-4g3o3aogr-sablier.vercel.app/concepts/use-cases#grants

**Comment by PaulRBerg** [comment]
Looks great, thanks @smol-ninja. Can we please move Airdrops at the top, right after Vesting? It's a more popular use case.
